# TrajectoryPlannerROS:
DWAPlannerROS:
  # Robot Configuration Parameters
  max_vel_x: 0.5
  min_vel_x: 0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 1.0
  min_vel_theta: 0.4

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  holonomic_robot: false

  # Goal Tolerance Parametes
  xy_goal_tolerance: 0.25
  yaw_goal_tolerance: 0.5
  latch_xy_goal_tolerance: true

  # Forward Simulation Parameters
  sim_time: 3.0
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 20.0

  # Debugging
  publish_traj_pc: true
  publish_cost_grid_pc: true

  # evaluating
  path_distance_bias: 200
  goal_distance_bias: 24
