global_costmap:
  global_frame: map
  robot_base_frame: base_link

  # update_frequency: 1.0
  # publish_frequency: 1.0

  # static_map: true
  # rolling_window: true
  width: 100.0
  height: 100.0
  resolution: 0.25
  origin_x: -50
  origin_y: -50
