local_costmap:
  global_frame: map
  robot_base_frame: base_link

  update_frequency: 5.0
  publish_frequency: 5.0

  # if using real-time processed obstacle points
  # observation_sources: scan
  # scan/data_type: PointCloud2
  # scan/sensor_frame: base_link 
  # scan/topic: obstacle_points 
  # scan/marking: true 
  # scan/clearing: true
  # scan/expected_update_rate: 0.15
  # scan/obstacle_range: 5.0
  # scan/raytrace_range: 5.0


  static_map: true
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.1

  # plugins:
  #  - {name: local/static_layer,   type: "costmap_2d::StaticLayer"}
  #  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  #  - {name: inflation_layer,type: "costmap_2d::InflationLayer"}

  
