DWAPlannerROS:
  # Robot Configuration Parameters
  max_vel_x: 2.0
  max_vel_x_backwards: 0.2
  max_vel_y: 0
  min_vel_y: 0
  acc_lim_y: 0
  max_vel_theta: 1.5
  acc_lim_x: 0.25
  acc_lim_theta: 0.5
  # min_turning_radius: 0.1
  min_turning_radius: 0
  wheelbase: 0.1
