local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0


  static_map: true
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.25

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
  #   - {name: lidar, type: "costmap_2d::ObstacleLayer"}
  #   - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}
  
  # lidar:
  #   observation_sources: scan
  #   scan/topic: /obstacles
  #   scan/data_type: PointCloud2
  #   scan/sensor_frame: base_link
  #   scan/marking: true
  #   scan/clearing: true
  #   scan/obstacle_range: 5.0
  #   scan/min_obstacle_height: -0.5
