base_global_planner: global_planner/GlobalPlanner
base_local_planner: teb_local_planner/TebLocalPlannerROS
#dwa_local_planner/DWAPlannerROS
#teb_local_planner/TebLocalPlannerROS

controller_frequency: 10
planner_patience: 5
controller_patience: 15
planner_frequency: 0
recovery_behavior_enabled: false

GlobalPlanner/use_dijkstra: true

