TebLocalPlannerROS:
  # Robot Configuration Parameters
  max_vel_x: 0.7
  max_vel_x_backwards: 0.2
  max_vel_y: 0
  acc_lim_y: 0
  max_vel_theta: 1.5
  acc_lim_x: 0.25
  acc_lim_theta: 0.5
  min_turning_radius: 0.1
  wheelbase: 0.1
  
  allow_init_with_backwards_motion: false
  cmd_angle_instead_rotvel: false

  # Goal Tolerance Parametes
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.25
  free_goal_vel: true

  # Forward Simulation Parameters
  sim_time: 5.0
  vx_samples: 10
  vy_samples: 0
  vth_samples: 10
  controller_frequency: 10.0

  # Debugging
  publish_traj_pc: true
  publish_cost_grid_pc: true

  # optimization
  global_plan_viapoint_sep: 1.0
  global_plan_overwrite_orientation: true
  weight_viapoint: 0.1
  weight_kinematics_forward_drive: 1000
  weight_obstacle: 20
  weight_kinematics_turning_radius: -0.01
  weight_max_vel_x: -0.01
  weight_acc_lim_x: 0.05
  min_obstacle_dist: 0.015
  

  # obstacles
  # costmap_converter_plugin: costmap_converter::CostmapToPolygonsDBSConcaveHull
  # costmap_converter_plugin: costmap_converter::CostmapToPolygonsDBSMCCH
  # costmap_converter/CostmapToPolygonsDBSConcaveHull/cluster_max_distance: 0.2
  # costmap_converter/CostmapToPolygonsDBSConcaveHull/cluster_min_pts: 10
  # costmap_converter/CostmapToPolygonsDBSConcaveHull/cluster_max_pts: 1000
  # costmap_converter/CostmapToPolygonsDBSConcaveHull/concave_hull_depth: 20.0
  # costmap_converter/CostmapToPolygonsDBSConcaveHull/convex_hull_min_pt_separation: 2.0



  feasibility_check_no_poses: 0
  max_global_plan_lookahead_dist: 0
